import type { Item } from "@/types/item";
import type { ItemBlock } from "@/types/itemBlock";

    export const demoBlocks: ItemBlock[] = [
    {
        id: 'b1',
        type: 'text',
        text: 'Welcome to our new collection launch!',
        style: { fontSize: '12px', fontWeight: 'bold', color: '#333' },
        orderIndex: 0,
        createdAt: '2025-11-06T09:00:00.000Z',
        updatedAt: '2025-11-06T09:00:00.000Z',
    },
    {
        id: 'b2',
        type: 'image',
        url: 'https://nest-library-api-mahwayji.s3.ap-southeast-2.amazonaws.com/images/IThinkINeedMoreCoffee.jpeg',
        alt: 'Modern furniture set',
        caption: 'Our minimalist furniture collection',
        aspectRatio: '16:9',
        orderIndex: 1,
        createdAt: '2025-11-06T09:05:00.000Z',
        updatedAt: '2025-11-06T09:10:00.000Z',
    },
    {
        id: 'b3',
        type: 'text',
        text: 'Each piece is crafted with sustainable materials for long-lasting comfort.',
        style: { fontSize: '14px', lineHeight: '1.5' },
        orderIndex: 2,
        createdAt: '2025-11-06T09:15:00.000Z',
        updatedAt: '2025-11-06T09:15:00.000Z',
    },
    {
        id: 'b4',
        type: 'video',
        url: 'https://nest-library-api-mahwayji.s3.ap-southeast-2.amazonaws.com/images/weird_ass_bunny.mp4',
        controls: true,
        muted: false,
        width: 500,
        height: 500,
        orderIndex: 3,
        createdAt: '2025-11-06T09:20:00.000Z',
        updatedAt: '2025-11-06T09:25:00.000Z',
    },
    {
        id: 'b5',
        type: 'image',
        url: 'https://nest-library-api-mahwayji.s3.ap-southeast-2.amazonaws.com/images/coolRacoon.gif',
        alt: 'Modern furniture set',
        caption: 'Our minimalist furniture collection',
        aspectRatio: '16:9',
        orderIndex: 1,
        createdAt: '2025-11-06T09:05:00.000Z',
        updatedAt: '2025-11-06T09:10:00.000Z',
    },
    ];


    export const demoItems: Item[] = [
    {
        id: "item-001",
        sectionId: "section-01",
        title: "Introduction to React",
        description: "A beginner-friendly overview of React components and JSX.",
        tags: ["react", "frontend", "javascript"],
        thumbnail: "https://example.com/thumbnails/react-intro.png",
        orderIndex: 1,
        blocks: demoBlocks,
        createdAt: new Date("2024-10-01T10:00:00Z"),
        updatedAt: new Date("2024-10-05T12:00:00Z"),
    },
    {
        id: "item-002",
        sectionId: "section-02",
        title: "Advanced TypeScript",
        description: "Deep dive into TypeScript’s advanced typing features.",
        tags: ["typescript", "advanced", "frontend"],
        thumbnail: "https://example.com/thumbnails/ts-advanced.png",
        orderIndex: 2,
        blocks: demoBlocks,
        createdAt: new Date("2024-10-10T14:00:00Z"),
        updatedAt: new Date("2024-10-12T09:30:00Z"),
    },
    {
        id: "item-003",
        sectionId: "section-03",
        title: "Building a REST API",
        description: "Learn to design and build RESTful APIs using Node.js and Express.",
        tags: ["nodejs", "backend", "api"],
        thumbnail: "https://example.com/thumbnails/rest-api.png",
        orderIndex: 3,
        blocks: demoBlocks,
        createdAt: new Date("2024-11-01T09:00:00Z"),
        updatedAt: new Date("2024-11-03T17:45:00Z"),
    },
    ];